# Generated by Django 3.1.3 on 2020-11-24 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuariomodel',
            name='usuCel',
            field=models.CharField(db_column='usu_cel', max_length=13, null=True),
        ),
        migrations.AlterField(
            model_name='usuariomodel',
            name='usuApellido',
            field=models.CharField(db_column='usu_apellido', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='usuariomodel',
            name='usuDni',
            field=models.CharField(db_column='usu_dni', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='usuariomodel',
            name='usuNombre',
            field=models.CharField(db_column='usu_nombre', max_length=50, null=True),
        ),
    ]
